# Fuzzel launcher config.
# Taken from driftwm (https://github.com/malbiruk/driftwm).

[main]
font=monospace:size=11
icons-enabled=no

[colors]
background=2e2e2eb3
text=b3b3b3ff
input=b3b3b3ff
prompt=b3b3b3ff
match=ffffffff
placeholder=b3b3b3ff
selection=00000000
selection-text=ffffffff
selection-match=ffffffff
border=2e2e2eb3
